baseURL = "https://www.didida.top/"
languageCode = "en-us"
title = "滴滴哒的技术分享"
theme = "learn"

pluralizeListTitles = false

author = "Augustu Scofield"
copyright = "© Augustu Scofield 2021"

[outputs]
home = [ "HTML", "RSS", "JSON"]
